language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"

install:
 - pip install -r requirements-test.txt
 - pip install coverage

script: coverage run manage.py test

after_success:
  - coverage report
  - pip install --quiet python-coveralls
  - coveralls
